### ISSUE TITLE
GeoNode Demos

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/geonode#713]
The current https://master.demo.geonode.org/ is using the stable branch of GeoNode (3.2.x), since the master branch is going to be quite unstable from now on.
We need a new machine to test the master branch. This requires:

- [x] creating a new machine to host the master branch
- [x] create a new DNS record stable.demo.geonode.org for 188.165.216.96
- [x] configure the current master demo GN instance to use the stable.demo.geonode.org domain
- [x] change the [demo page](http://demo.geonode.org/) to reference the stable.demo.geonode.org
- [x] assign the master.demo.geonode.org DNS to the new master demo IP

**Comment by giohappy** [comment]
@randomorder according to what have been discussed in [this document](https://docs.google.com/document/d/1ngiCGXLR8j_-YugfwGhkOkX0Dl5NPctelWp4-5W8ZNY) we should proceed quickly with the following instances:

- **stable.demo.geonode.org**: 3.2.x branch
- **master.demo.geonode.org**: master branch 

dev.demo.geonode.org will be possibly created for 3.3.x, but I would wait to do it.

**Comment by agpenton** [comment]
@randomorder Please i need access to where those VMs are located, as well as the CI where the pipeline are.

**Comment by randomorder** [comment]
stable.demo instance will be hosted on the current master.demo

please report current usage of hardware resources of the master instance here @agpenton 
we need to decide if we need to get a dedicated machine to host it

**Comment by agpenton** [comment]
@randomorder 

Resources used in the server.
**space usage:**
```shell
df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/root        20G  9.2G  9.0G  51% /
devtmpfs         16G     0   16G   0% /dev
tmpfs            16G  4.0K   16G   1% /dev/shm
tmpfs            16G  1.8G   14G  12% /run
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs            16G     0   16G   0% /sys/fs/cgroup
/dev/md1        487M   23M  435M   5% /boot
/dev/md3        200G   98G   93G  52% /home
```

**Memory usage:**
```shell
              total        used        free      shared  buff/cache   available
Mem:            31G        7.8G        1.8G        1.4G         21G         21G
Swap:          1.0G        561M        460M
```

**CPU usage:**
```shell
Linux 4.9.78-xxxx-std-ipv6-64 (geonode-demo) 	05/24/2021 	_x86_64_	(8 CPU)

02:09:12 PM  CPU    %usr   %nice    %sys %iowait    %irq   %soft  %steal  %guest  %gnice   %idle
02:09:12 PM  all   13.82    0.00    4.01    0.03    0.00    0.05    0.00    0.00    0.00   82.09
02:09:12 PM    0   31.50    0.00    8.01    0.06    0.00    0.07    0.00    0.00    0.00   60.36
02:09:12 PM    1   11.80    0.00    3.69    0.03    0.00    0.06    0.00    0.00    0.00   84.42
02:09:12 PM    2   13.04    0.00    3.94    0.02    0.00    0.05    0.00    0.00    0.00   82.95
02:09:12 PM    3   13.63    0.00    4.16    0.02    0.00    0.04    0.00    0.00    0.00   82.16
02:09:12 PM    4    8.43    0.00    2.13    0.02    0.00    0.03    0.00    0.00    0.00   89.39
02:09:12 PM    5   12.46    0.00    3.83    0.02    0.00    0.06    0.00    0.00    0.00   83.64
02:09:12 PM    6   11.31    0.00    3.59    0.01    0.00    0.03    0.00    0.00    0.00   85.06
02:09:12 PM    7    8.40    0.00    2.74    0.07    0.00    0.05    0.00    0.00    0.00   88.73
```

Resources used for master-demo stack:

![Screen Shot 2021-05-24 at 16.15.41.png](https://images.zenhubusercontent.com/60099e6b79174e627d511373/722b4839-6885-450c-a0a4-356fe819db8f)

**Comment by randomorder** [comment]
I though we were deploying a geonode-project from the master branch on master demo @giohappy
instead I see https://github.com/GeoNode/geonode_master.git on the 3.2.x branch

We need to talk about it before moving on with the implementation

**Comment by giohappy** [comment]
The current master demo is using branch 3.2.x of geonode_master project, but the master branch of it is [referencing geonode maser](url).

As agreed the new **master** demo will be really the master branch.

**Comment by randomorder** [comment]
@agpenton please move on with the setup of the new PVH machine carefully documenting each step

**Comment by randomorder** [comment]
@giohappy @etj I've updated the GDoc with the outcome of our discussion earlier today

**Comment by agpenton** [comment]
@randomorder the new server is configured, the stack of geonode-master is migrated, and running. The documentation till this moment I will finish on Monday.
then I will create the CI/CD for the project.

**Comment by agpenton** [comment]
@randomorder @afabiani about the CI/CD:
- can you explain to me the workflow of the pipeline?
- which images need to be built in the pipeline?

**Comment by randomorder** [comment]
updates @agpenton ?
please link the documentation for the machine here as well

**Comment by agpenton** [comment]
@randomorder after the creation of the environment, and spun up with the commands in the documentation, I ran to an issue with geoserver, cause look like is running normal, and suddenly just stop with exit code 143. I mounted the tomcat logs directory and geoserver log directory, which one is empty, then I tried to run an instance of the geoserver image to investigate the cause of why the logs were empty, and I found that the "/var/geoserver" doesn't exist, and the geoserver-data is placed to another location "/geoserver_data/data".  Another thing to mention is that the geonode takes a long time to be healthy, and just get that state if the geoserver is running at the moment that it requests data from it so meanwhile, the Nginx gives a 502 error. 
this is the link to the documentation: https://docs.google.com/document/d/18PaJTH-Absl7xw4lRkDgBoHkEoyN57dOrpXbCS8mOD0/edit#heading=h.v5qjoqj3tphp

this is a screenshot of the 
![Screen Shot 2021-06-08 at 19.43.19.png](https://images.zenhubusercontent.com/60099e6b79174e627d511373/2344f90b-21f5-4200-8cfa-5b4356bf5b3d)

**Comment by agpenton** [comment]
@randomorder the environment for the new server works well, as the build, yesterday the watchdog was restarting the geoserver.  can you add the IP of the new server to the second domain **stable.demo.geonode.org**, so we can enable the watchdog, and test it.

**Comment by randomorder** [comment]
this new machine is going to host `master.demo.geonode.org`, not the stable version

what's missing to be able to switch the DNS record from the original machine to this one?

**Comment by agpenton** [comment]
well, we need to migrate the data from the old server to this one.
Test that everything is ok, and then change the dns record.

**Comment by randomorder** [comment]
Updates @agpenton ?

**Comment by agpenton** [comment]
@randomorder the server is running as expected was an issue with the outdated jars, but now is resolved. the pipeline on the Jenkins server is running normally.

**Comment by agpenton** [comment]
@randomorder the monitoring system for the geonode master demo and  geonode stable demo is settled.

master demo http://monitoring.geo-solutions.it/resources?lang=en&tag=GeoNode%3A+master.demo.geonode.org

stable demo http://monitoring.geo-solutions.it/resources?lang=en&tag=GeoNode%3A+stable.demo.geonode.org

**Comment by agpenton** [comment]
@randomorder in master.demo.geonode.org I getting issues with WFS and WMS. Due to these problems with the layers and styles since https://github.com/geosolutions-it/geonode/issues/824, I'm disabling temporary these probes: 
- http://monitoring.geo-solutions.it/resource/395?lang=en
- http://monitoring.geo-solutions.it/resource/393?lang=en

till the issue get resolve.

**Comment by giohappy** [comment]
@agpenton as reported by chat I still see this problem on stable demo:

1 - login to Geoserver as an admin
2 - click on the GeoNode login button in Geoserver
3 - I receive an error

![image](https://user-images.githubusercontent.com/571129/122941772-fd587800-d375-11eb-9445-c859cdbe5d03.png)


![image](https://user-images.githubusercontent.com/571129/122941721-f0d41f80-d375-11eb-9377-b9fdee2a1c24.png)

**Comment by giohappy** [comment]
The redirect uri inside GeoNode had to be changed. Fixed.

![image](https://user-images.githubusercontent.com/571129/122947259-4f030180-d37a-11eb-971b-0dd17f761027.png)

**Comment by randomorder** [comment]
news about the geoserver issue and monitoring?

@agpenton please link here the documentation for both machines (stable and master)

**Comment by randomorder** [comment]
Adding to my comment above @agpenton
can you put in place a redirect from the master demo to this page:
http://geonode-back-soon.s3-website-us-west-2.amazonaws.com/redirect.html  ?

Use HTTP temporary redirect instead of permanent (code 302, not 301)

**Comment by agpenton** [comment]
> Adding to my comment above @agpenton
> can you put in place a redirect from the master demo to this page:
> http://geonode-back-soon.s3-website-us-west-2.amazonaws.com/redirect.html ?
> 
> Use HTTP temporary redirect instead of permanent (code 302, not 301)
ok...on it

**Comment by agpenton** [comment]
> > Adding to my comment above @agpenton
> > can you put in place a redirect from the master demo to this page:
> > http://geonode-back-soon.s3-website-us-west-2.amazonaws.com/redirect.html ?
> > Use HTTP temporary redirect instead of permanent (code 302, not 301)
> > ok...on it

done

**Comment by agpenton** [comment]
> news about the geoserver issue and monitoring?
> 
> @agpenton please link here the documentation for both machines (stable and master)

master demo
https://docs.google.com/document/d/18PaJTH-Absl7xw4lRkDgBoHkEoyN57dOrpXbCS8mOD0/edit#heading=h.3neyfim0i8xz

stable demo
https://docs.google.com/document/d/1cQ_UTU4N0aTHPQRbqo-0JFwxZavW72R5fgJ0OUiwrtA/edit#heading=h.3f8xflw2zp7e

**Comment by randomorder** [comment]
> stable demo
> https://docs.google.com/document/d/1cQ_UTU4N0aTHPQRbqo-0JFwxZavW72R5fgJ0OUiwrtA/edit#heading=h.3f8xflw2zp7e


Is this just a clone of the original Doc?

**Comment by agpenton** [comment]
> > stable demo
> > https://docs.google.com/document/d/1cQ_UTU4N0aTHPQRbqo-0JFwxZavW72R5fgJ0OUiwrtA/edit#heading=h.3f8xflw2zp7e
> 
> Is this just a clone of the original Doc?

i didn't change anything there.

**Comment by randomorder** [comment]
please check all my comments in the Doc

**Comment by randomorder** [comment]
still pending @agpenton ?

**Comment by agpenton** [comment]
the documents are updated, please let me know what else i need to change in the docs.

**Comment by randomorder** [comment]
still lots of pending comments
are we looking at the same doc?
https://docs.google.com/document/d/1cQ_UTU4N0aTHPQRbqo-0JFwxZavW72R5fgJ0OUiwrtA/edit#heading=h.xxrew09cah1

**Comment by randomorder** [comment]
@agpenton ? you're making this extraordinarily and unnecessarily painful
